custom_categories:
  - name: Handlers
    children:
      - LaunchEnvironmentManager
      - AnimationHandler
      - IsInUITestHandler
      - ContactsHandler
      - EventKitHandler
      - Handler
  - name: Parsers
    children:
      - ContactDictionaryParser
      - EventDictionaryParser
      - ReminderDictionaryParser
      - Parser
      - ContactParser
      - EventParser
      - ReminderParser
  - name: Interfaces
    children:
      - ContactsInterface
      - EventKitInterface
      - ContactsInterfaceProtocol
      - EventKitInterfaceProtocol
