custom_categories:
  - name: Handlers
    children:
      - LaunchEnvironmentManager
      - AnimationHandler
      - ContactsHandler
      - EventKitHandler
      - Handler
  - name: Parsers
    children:
      - ContactDictionaryParser
      - EventDictionaryParser
      - ReminderDictionaryParser
      - Parser
      - ContactParser
      - EventParser
      - ReminderParser
