language: objective-c
osx_image: xcode9.1

env:
  global:
    - NSUnbufferedIO=YES
  matrix:
    - SCHEME="AutoMate-AppBuddy iOS" PLATFORM="iOS Simulator"  DESTINATION_NAME="iPhone 7"       DESTINATION_OS="11.0"

before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint

before_script:
  - swiftlint version
  - bundle exec pod --version
  - bundle exec fastlane --version
  - bundle exec fastlane snapshot reset_simulators --force --ios 11.0

script:
  - bundle exec fastlane test "scheme:${SCHEME}" "destination:platform=${PLATFORM},name=${DESTINATION_NAME},OS=${DESTINATION_OS}"
  - bundle exec danger
  - bundle exec pod lib lint
