language: objective-c
osx_image: xcode8.3

env:
  global:
    - NSUnbufferedIO=YES
  matrix:
    - DESTINATION_NAME="iPhone 7"       DESTINATION_OS="10.3"

before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint

before_script:
  - swiftlint version
  - bundle exec pod --version
  - bundle exec fastlane --version
  - bundle exec fastlane snapshot reset_simulators --force --ios ${DESTINATION_OS}

script:
  - bundle exec fastlane test "destination:platform=iOS Simulator,name=${DESTINATION_NAME},OS=${DESTINATION_OS}"
  - bundle exec danger
  - bundle exec pod lib lint
